artifact_uri: s3://mlflow-artifacts/diabetes_readmission/51a777af8a1a47e9b9f27e9fee891165/artifacts
end_time: 1746230485605
entry_point_name: ''
experiment_id: '225220923780667378'
lifecycle_stage: active
run_id: 51a777af8a1a47e9b9f27e9fee891165
run_name: LogisticRegression
run_uuid: 51a777af8a1a47e9b9f27e9fee891165
source_name: ''
source_type: 4
source_version: ''
start_time: 1746230478598
status: 3
tags: []
user_id: airflow
