artifact_uri: s3://mlflow-artifacts/diabetes_readmission/c9d81335aead45ddafb66cb1404152d3/artifacts
end_time: 1746116553383
entry_point_name: ''
experiment_id: '225220923780667378'
lifecycle_stage: active
run_id: c9d81335aead45ddafb66cb1404152d3
run_name: LogisticRegression
run_uuid: c9d81335aead45ddafb66cb1404152d3
source_name: ''
source_type: 4
source_version: ''
start_time: 1746116542883
status: 3
tags: []
user_id: airflow
