aliases: []
creation_timestamp: 1746116532791
current_stage: None
description: ''
last_updated_timestamp: 1746116532791
name: diabetes_model
run_id: 26d4a33d67714bf09937978d3b813251
run_link: ''
source: s3://mlflow-artifacts/diabetes_readmission/26d4a33d67714bf09937978d3b813251/artifacts/model
status: READY
status_message: null
storage_location: s3://mlflow-artifacts/diabetes_readmission/26d4a33d67714bf09937978d3b813251/artifacts/model
user_id: null
version: 5
