aliases: []
creation_timestamp: 1746117151988
current_stage: None
description: ''
last_updated_timestamp: 1746117151988
name: diabetes_model
run_id: 4226efd35cb44063ab24f2d534d1f6e0
run_link: ''
source: s3://mlflow-artifacts/diabetes_readmission/4226efd35cb44063ab24f2d534d1f6e0/artifacts/model
status: READY
status_message: null
storage_location: s3://mlflow-artifacts/diabetes_readmission/4226efd35cb44063ab24f2d534d1f6e0/artifacts/model
user_id: null
version: 7
