artifact_uri: s3://mlflow-artifacts/diabetes_readmission/90d9c0dc62f04a74961a3c5af9ee815b/artifacts
end_time: 1746230464611
entry_point_name: ''
experiment_id: '225220923780667378'
lifecycle_stage: active
run_id: 90d9c0dc62f04a74961a3c5af9ee815b
run_name: RandomForest
run_uuid: 90d9c0dc62f04a74961a3c5af9ee815b
source_name: ''
source_type: 4
source_version: ''
start_time: 1746230411330
status: 3
tags: []
user_id: airflow
