aliases: []
creation_timestamp: 1746316884430
current_stage: Archived
description: ''
last_updated_timestamp: 1746403286548
name: diabetes_model
run_id: c6f4758cf05c4832895fed9cd6c47fa8
run_link: ''
source: s3://mlflow-artifacts/diabetes_readmission/c6f4758cf05c4832895fed9cd6c47fa8/artifacts/model
status: READY
status_message: null
storage_location: s3://mlflow-artifacts/diabetes_readmission/c6f4758cf05c4832895fed9cd6c47fa8/artifacts/model
user_id: null
version: 14
