aliases: []
creation_timestamp: 1746316857428
current_stage: None
description: ''
last_updated_timestamp: 1746316857428
name: diabetes_model
run_id: e8673aef06c44f0fb429504f84b62d4e
run_link: ''
source: s3://mlflow-artifacts/diabetes_readmission/e8673aef06c44f0fb429504f84b62d4e/artifacts/model
status: READY
status_message: null
storage_location: s3://mlflow-artifacts/diabetes_readmission/e8673aef06c44f0fb429504f84b62d4e/artifacts/model
user_id: null
version: 13
