# --- DEPLOYMENT inference-api ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-api
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-api
  template:
    metadata:
      labels:
        app: inference-api
    spec:
      containers:
        - name: inference
          image: mariamon/inference-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: MODEL_NAME
              value: diabetes_model
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

---
# --- SERVICE inference-api ---
apiVersion: v1
kind: Service
metadata:
  name: inference-api
  namespace: mlops
spec:
  selector:
    app: inference-api
  ports:
    - port: 8000
      targetPort: 8000

