apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: mariamon/mlflow:latest
          ports:
            - containerPort: 5000
          env:
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
          command:
            [
              "mlflow", "server",
              "--backend-store-uri", "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow",
              "--default-artifact-root", "s3://mlflow-artifacts",
              "--host", "0.0.0.0",
              "--port", "5000"
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlops
spec:
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000

