apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30432
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-nodeport
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - name: mlflow
      port: 5000
      targetPort: 5000
      nodePort: 30500
---
apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: minio-api
      port: 9000
      targetPort: 9000
      nodePort: 30900

