aliases: []
creation_timestamp: 1746112210471
current_stage: None
description: ''
last_updated_timestamp: 1746112210471
name: diabetes_model
run_id: 3e62be72f0e343188607f1a447df8571
run_link: ''
source: s3://mlflow-artifacts/diabetes_readmission/3e62be72f0e343188607f1a447df8571/artifacts/model
status: READY
status_message: null
storage_location: s3://mlflow-artifacts/diabetes_readmission/3e62be72f0e343188607f1a447df8571/artifacts/model
user_id: null
version: 2
