aliases: []
creation_timestamp: 1746117173712
current_stage: Archived
description: ''
last_updated_timestamp: 1746144086301
name: diabetes_model
run_id: 66942daecb954c3da80045d6732bf433
run_link: ''
source: s3://mlflow-artifacts/diabetes_readmission/66942daecb954c3da80045d6732bf433/artifacts/model
status: READY
status_message: null
storage_location: s3://mlflow-artifacts/diabetes_readmission/66942daecb954c3da80045d6732bf433/artifacts/model
user_id: null
version: 8
