aliases: []
creation_timestamp: 1746230464021
current_stage: None
description: ''
last_updated_timestamp: 1746230464021
name: diabetes_model
run_id: 90d9c0dc62f04a74961a3c5af9ee815b
run_link: ''
source: s3://mlflow-artifacts/diabetes_readmission/90d9c0dc62f04a74961a3c5af9ee815b/artifacts/model
status: READY
status_message: null
storage_location: s3://mlflow-artifacts/diabetes_readmission/90d9c0dc62f04a74961a3c5af9ee815b/artifacts/model
user_id: null
version: 11
